// This code automatically generated by TableCodeGen
using UnityEngine;
using System.Collections;
using System.Collections.Generic;
using Signals;
using System;
using Data.UnityObject;
using Data.ValueObject;

public class PlayerManager : MonoBehaviour
{

	#region Self Variables
	#region Public Variables
	#endregion

	#region SerializeField Variables
	[SerializeField] private float playerInitialPosY = 0.5f, playerCurrentPos = 0.5f, startBlockCount = 5;

	#endregion

	#region Private Variables
	private PlayerData _data;
	#endregion
	#endregion
	private void Awake()
	{
		Init();
	}

    private void Init()
    {
		_data = GetData();
    }

	private PlayerData GetData() => Resources.Load<CD_Player>("Data/CD_Player").Data;
    #region Event Subscriptions

    private void OnEnable()
	{
		SubscribeEvents();
	}

	private void SubscribeEvents()
	{
		PlayerSignals.Instance.onPlayerAnsweredRight += OnPlayerAnsweredRight;
		CoreGameSignals.Instance.onRestartLevel += OnRestartLevel;
    }

	private void UnsubscribeEvents()
	{
		PlayerSignals.Instance.onPlayerAnsweredRight -= OnPlayerAnsweredRight;
		CoreGameSignals.Instance.onRestartLevel -= OnRestartLevel;
	}

	private void OnDisable()
	{
		UnsubscribeEvents();
	}

    #endregion

    private void Start()
    {
		StartMove();
	}
	private void StartMove()
    {
		//playerCurrentPos += startBlockCount;
		//transform.position = new Vector3(0, playerCurrentPos, 5);
    }

	private void OnPlayerAnsweredRight(int charCount)
    {
		//transform.position = new Vector3(0, playerInitialPosY + charCount, 5);
    }
	private void OnRestartLevel()
    {
		transform.position = _data.InitialPos;
    }


}