// This code automatically generated by TableCodeGen
using UnityEngine;
using System.Collections;
using System.Collections.Generic;
using Signals;

public class QuestionManager : MonoBehaviour
{

	#region Self Variables
	#region Public Variables
	#endregion

	#region SerializeField Variables
	[SerializeField] private int questionId = 0;
	#endregion

	#region Private Variables
	#endregion
	#endregion
	private void Awake()
	{
	}
	#region Event Subscriptions

	private void OnEnable()
	{
		SubscribeEvents();
	}

	private void SubscribeEvents()
	{
        QuestionSignals.Instance.onGetQuestionId += OnGetQuestionId;
    }

	private void UnsubscribeEvents()
	{
        QuestionSignals.Instance.onGetQuestionId -= OnGetQuestionId;
    }

	private void OnDisable()
	{
		UnsubscribeEvents();
	}

    #endregion

    private void Start()
    {
		AskQuestion();
	}
	public void AskQuestion()
	{
		QuestionSignals.Instance.onAskQuestion?.Invoke(questionId);
	}

	public int OnGetQuestionId()
	{
		return questionId;
	}

}