// This code automatically generated by TableCodeGen
using UnityEngine;
using System.Collections;
using System.Collections.Generic;
using Signals;

public class QuestionManager : MonoBehaviour
{

	#region Self Variables
	#region Public Variables
	#endregion

	#region SerializeField Variables
	[SerializeField] private int questionId = 0;
	[SerializeField] private Transform waterTransform;
	#endregion

	#region Private Variables
	#endregion
	#endregion
	private void Awake()
	{
	}
	#region Event Subscriptions

	private void OnEnable()
	{
		SubscribeEvents();
	}

	private void SubscribeEvents()
	{
        QuestionSignals.Instance.onGetQuestionId += OnGetQuestionId;
		QuestionSignals.Instance.onPlayerHitEnterButton += OnShowAnswerInPanel;
    }

	private void UnsubscribeEvents()
	{
        QuestionSignals.Instance.onGetQuestionId -= OnGetQuestionId;
		QuestionSignals.Instance.onPlayerHitEnterButton -= OnShowAnswerInPanel;
	}

	private void OnDisable()
	{
		UnsubscribeEvents();
	}

    #endregion

    private void Start()
    {
		AskQuestion();
	}
	public void AskQuestion()
	{
		QuestionSignals.Instance.onAskQuestion?.Invoke(questionId);
	}

	private void OnShowAnswerInPanel(string text)
    {
		StartCoroutine(WaterRising());
    }
	private IEnumerator WaterRising()
    {
		yield return new WaitForSeconds(1f);
		waterTransform.position += new Vector3(0, 3, 0);

	}

	public int OnGetQuestionId()
	{
		return questionId;
	}

}